kind: pipeline
type: docker
name: MangaMap

trigger:
  event:
    - push

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:7.0
    volumes:
      - name: Documentation
        path: /Documentation
    commands:
      - cd MangaMap/
      - dotnet restore MangaMap.sln
      - dotnet build MangaMap.sln -c Release --no-restore 
      - dotnet publish SolutionTest.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release



volumes:
- name: docs
  temp: {}