kind: pipeline
type: docker
name: CI Workflow

steps:
  - name: Build
    image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dotnet7-maui:latest
    commands:
      - dotnet test --framework net7.0 'Tests\\\\Tests.csproj'